CREATE TABLE IF NOT EXISTS '#__golestan_departed' (
	'departed_id' int(11) NOT NULL AUTO_INCREMENT,
	'fname' varchar(60) DEFAULT NULL,
	'lname' varchar(60) NOT NULL,
	'father_name' varchar(60) NOT NULL,
	'mother_name' varchar(60) DEFAULT NULL,
	'spouse_fname' varchar(60) DEFAULT NULL,
	'spouse_lname' varchar(60) DEFAULT NULL,
	'gender' varchar(1) DEFAULT NULL,
	'birth_date' datetime DEFAULT NULL,
	'birth_place' varchar(60) DEFAULT NULL,
	'death_date' datetime NOT NULL,
	'age' int NOT NULL,
	'cemetery' varchar(50) NOT NULL,
	'makan' int DEFAULT NULL,
	'gheteh' int DEFAULT NULL,
	'radif' int DEFAULT NULL,
	'sotoon' int DEFAULT NULL,
	'image' varchar(255) DEFAULT NULL,
	'publish_date' varchar(255) DEFAULT NULL,
	'created' datetime NOT NULL,
	'modified' datetime NOT NULL,
	'published' tinyint(2) DEFAULT 0,
	PRIMARY KEY ('departed_id`)
);